export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const SET_ERROR = 'SET_ERROR';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT_TITLE = 'SET_PRODUCT_TITLE';
export const SET_PRODUCT_ITEM = 'SET_PRODUCT_ITEM';
